'SqlBulkCopy.vb
'Author: https://github.com/crystalyun
'Description: This VB.net code inserts all rows from a UiPath Datatable into a MS SQL Database using SqlBulkCopy

'Arguments:
'in_str_DatabaseConnection: the database connection string
'in_int_BatchSize: the batch size to be used (50 is a good starting point)
'in_dict_ColumnMap: a Dictionary(String,String) of column mappings with Key = origin column name, Value = destination column name.  Include these even if column names are identical.
'in_str_TableName: the name of database table that records will be inserted into
'in_dt_SourceData: the Datatable to be inserted
'out_str_ExceptionMsg: the exception message generated by the SqlBulkCopy operation
'out_int_RowsInserted: the number of rows successfully inserted

Using dbConnection As New SqlConnection(in_str_DatabaseConnection)
    dbConnection.Open()
    Using rowCount As New SqlCommand("SELECT COUNT(*) FROM dbo." + in_str_TableName + ";", dbConnection)
    	Dim rowStart As Int32 = System.Convert.ToInt32(rowCount.ExecuteScalar())
	    Using dbCopy As New SqlBulkCopy(dbConnection)
	        dbCopy.BatchSize = in_int_BatchSize
            For Each entry As KeyValuePair(Of String, String) In in_dict_ColumnMap
	            dbCopy.ColumnMappings.Add(entry.Key, entry.Value)
	        Next
	        dbCopy.DestinationTableName = in_str_TableName
            Try
                dbCopy.WriteToServer(in_dt_SourceData)
            Catch ex As Exception
                out_str_ExceptionMsg = ex.Message
            Finally
                dbCopy.Close()
            End Try
	    End Using
	    Dim rowEnd As Int32 = System.Convert.ToInt32(rowCount.ExecuteScalar())
	    out_int_RowsInserted = rowEnd - rowStart
	End Using
    dbConnection.Close()
End Using